[package]
name = "pipewrench"
version = "0.1.0"
authors = ["Gavin Massey <mdk@mystacktrace.org>"]

[dependencies]
glium_sdl2="0.6.0"
sdl2 = "0.8.0"
image = "0.3.9"
toml = "0.1.22"
num = "0.1.27"
nalgebra = "0.3.0"

[dependencies.glium]
features = ["image", "nalgebra"]
default-features = false
